#!/bin/sh
#
# Installer/Updater for the Speckle Instrument drivers and GUI
#
export SPECKLE_DIR=${HOME}/speckle-control

echo ""
echo "-------------------------------------------------------------"
echo "Installing/Upgrading Andor Linux support"
echo "-------------------------------------------------------------"
echo ""
cd $HOME/speckle-control/lib
exec rm -fr libandor* libUSBI2C* libshamrockcif*
cd $HOME/speckle-control/andor
exec rm -fr andor.tgz andor-driver
wget http://www.randomfactory.com/speckle/andor.tgz
tar xzf andor.tgz
mv andor andor-driver
cd andor-driver
sudo ./install_andor

cd ..
rm -fr andorTclInit.so
./buildlib
if [ ! -f andorTclInit.so ]; then 
  echo ""
  echo "-----------------------------------------------------------"
  echo "Failed to build andorTclInit.so using andor/buildlib"
  echo "-----------------------------------------------------------"
  echo ""
  exit
fi
mv andorTclInit.so ../lib/.
cd ..

echo "Test environment and do an inventory of connected hardware"
./setDevicePermissions
./startspeckle2 test
export INVENTORY_EXIT=1
$SPECKLE_DIR/gui-scripts/inventory.tcl
unset INVENTORY_EXIT

echo ""
echo "-------------------------------------------------------------"
echo "If this is a new Installation, please update the Andor Camera"
echo "and Filter Wheel serial numbers in the appropriate site"
echo "specific andorsConfiguration files."
echo "Details can be found in the Programmers Guide"
echo "-------------------------------------------------------------"
echo ""


