#!/bin/sh

export TELESCOPE=GEMINI
export NESSI_DIR=$HOME/speckle-control
export PKG_CONFIG_PATH=$NESSI_DIR/pkgconfig
export PATH=${NESSI_DIR}/bin:${PATH}
export LD_LIBRARY_PATH=${NESSI_DIR}/lib:${LD_LIBRARY_PATH}
export NESSI_DATADIR=$HOME/data
export XPA_METHOD=local
xpans &
ds9 &
$NESSI_DIR/wiyn-scripts/gui.tcl

