#!/bin/sh

export TELESCOPE=WIYN
export SPECKLE_DIR=$HOME/speckle-control
export PKG_CONFIG_PATH=$SPECKLE_DIR/pkgconfig
export PATH=${SPECKLE_DIR}/bin:${PATH}
export LD_LIBRARY_PATH=${SPECKLE_DIR}/lib:${LD_LIBRARY_PATH}
export SPECKLE_DATADIR=$HOME/data
export XPA_METHOD=local
pkill -9 wish
xpans &
ds9red &
ds9blue &
$SPECKLE_DIR/gui-scripts/gui2.tcl

