#!/bin/sh

export NESSI_DIR=/home/rfactory/nessi-control
export PATH=${NESSI_DIR}/bin:${PATH}
export LD_LIBRARY_PATH=${NESSI_DIR}/lib:${LD_LIBRARY_PATH}
export XPA_METHOD=local
$NESSI_DIR/wiyn-scripts/gui.tcl

