#!/usr/bin/tclsh

# descriptor type
set USB(DESC_TYPE_DEVICE) 0x01
set USB(DESC_TYPE_CONFIG) 0x02
set USB(DESC_TYPE_STRING) 0x03
set USB(DESC_TYPE_INTERFACE) 0x04
set USB(DESC_TYPE_ENDPOINT) 0x05

# endpoint direction
set USB(ENDPOINT_IN) 0x80
set USB(ENDPOINT_OUT) 0x00

# endpoint type
set USB(ENDPOINT_TYPE_CTRL) 0x00
set USB(Eset USB(NDPOINT_TYPE_ISO) 0x01
set USB(ENDPOINT_TYPE_BULK) 0x02
set USB(ENDPOINT_TYPE_INTR) 0x03

# control request type
set USB(CTRL_TYPE_STANDARD)  0
set USB(CTRL_TYPE_CLASS)    32
set USB(CTRL_TYPE_VENDOR)   64
set USB(CTRL_TYPE_RESERVED) 96

# control request recipient
set USB(CTRL_RECIPIENT_DEVICE) 0
set USB(CTRL_RECIPIENT_INTERFACE) 1
set USB(CTRL_RECIPIENT_ENDPOINT) 2
set USB(CTRL_RECIPIENT_OTHER) 3

# control request direction
set USB(CTRL_OUT) 0x00
set USB(CTRL_IN) 0x80

set USB(_ENDPOINT_ADDR_MASK) 0x0f
set USB(_ENDPOINT_DIR_MASK) 0x80
set USB(_ENDPOINT_TRANSFER_TYPE_MASK) 0x03
set USB(_CTRL_DIR_MASK) 0x80

# speed type
set USB(SPEED_LOW) 1
set USB(SPEED_FULL) 2
set USB(SPEED_HIGH) 3
set USB(SPEED_SUPER) 4
set USB(SPEED_UNKNOWN) 0


