# makefile of GigE SDK Sample code
#

include ../ARCH

## Executable
EXE	= Stream2Fits
    
$(OBJ_DIR)/%.o : %.cpp
	$(CC) $(CFLAGS) -fpermissive $(VERSION) -c $< -o $@

clean: 
	rm $(EXE)

sample : $(EXE).cpp
	$(CC) $(RPATH) $(TARGET) $(CFLAGS) $(EXE).cpp -o $(EXE) $(SOLIB) $(PVLIB) -lcfitsio

sample-static : $(EXE).cpp
	$(CC) $(RPATH) $(TARGET) $(CFLAGS) $(EXE).cpp $(SALIB) -o $(EXE) $(SOLIB) -lcfitsio
	
install:
	cp -f $(EXE) $(BIN_DIR)
